import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { noto } from "@/font";
import SessionWrapper from "@/util/SessionWrapper";
import Navbar from "./ui/common/Navbar";
import Footer from "./ui/common/Footer";
import StoreProvider from "./StoreProvider";
import AuthSession from "./auth/AuthSession";
import QueryProvider from "./QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <SessionWrapper>
        <AuthSession>
          <html lang="en">
            <body className={noto.className}>
              <StoreProvider>
                <Navbar />
                {children}
                <Footer />
              </StoreProvider>
            </body>
            <Script
              type="text/javascript"
              src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_MAP_CLIENT_ID}`}
            ></Script>
          </html>
        </AuthSession>
      </SessionWrapper>
    </QueryProvider>
  );
}
